<?php
require_once(__DIR__.'/inc/init.php');

define('SITE_TITLE', 'Kullanım Koşulları | '.$conf["site_name"]);
define('SITE_DESCRIPTION', $conf["site_name"].' kullanım koşulları bu sayfa altında yer almaktadır.');
define('SITE_KEYWORDS', '');
define('SITE_ROBOTS', 'INDEX, FOLLOW');

// Header
require_once(__DIR__.'/inc/header.php');
require_once(__DIR__.'/themes/'.THEME.'/header-template.php');
?>
<section class="container content terms">
    <section class="section">
        <h2>Site Kullanım Koşulları</h2>
        <hr>
        <p><u><?php echo $conf["site_name"]; ?></u>'den faydalanan herkes bu şartlardan sorumludur. Aksi takdirde kullanıcılardan dolayı doğabilecek olan tüm sorumlulukları <u><?php echo $conf["site_name"]; ?></u> yetkilileri kabul etmeyecektir. Tüm sorumlulukları reddetmemizin sebepleri aşağıdaki kurallarda açıkca belirtilmiştir. Kabul etmeyen kullanıcıların <u><?php echo $conf["site_name"]; ?></u> hizmetlerinden faydalanmalarını tavsiye etmiyoruz.</p>
        <h3>1. Hizmetlerimiz</h3>
        <p>Görevimiz; ziyaretçilere, üyelerimize hızlı ve stabil çalışan bir anasayfa hizmeti sunmak istiyoruz. Birçok hizmeti bir araya toplayıp bir sayfada sizlere sunmayı amaçlıyoruz.</p>
        <p><strong>Kişiselleştirilmiş arayüz hizmeti:</strong> Bu arayüz sayesinde, istediğiniz öğeleri ekranın istediğiniz konumuna paylaştırabilirsiniz. İstediğinizi hizmeti anasayfanızda görebilir, İstemediğiniz hizmeti devredışı bırakabilir ve kullanımını engelleyebilirsiniz. Ancak sadece bir istisna dışında tüm hizmetleri devre dışı bırakabilir ve aktifleştirebilirsiniz. Sadece "Arama Motoru" hizmeti devre dışı bırakılamaz, aktifleştirilemez, sürüklenemez ve yer değiştirilemez.</p>
        <p><strong>Birçok hizmet tek bir sayfada:</strong> Arama Motoru, Hava Durumu, Haberler, Not Defteri, Takvim gibi geliştirilen birçok özelliği sizlere sunuyoruz. Kullanıp kullanmamak sizlere kalmış. "Özelleştir" sayfasından istediğiniz özelliği ekleyebilir, çıkarabilir, sürükleyebilirsiniz. "Kişiselleştirilmiş arayüz hizmeti" bölümünde bahsedildiği gibi "Arama Motoru" istisnadır.</p>
        <p><strong>Kullanılan hizmetler:</strong><u><?php echo $conf["site_name"]; ?></u>'de bulunan ve başka sitelerden temin edilen hizmetlerin kendilerine ait kuralları olabilir. Bu kuralları ihlal eden kullanıcılar, sebep belirtilmediği sürece cezalandırılmayacaktır.</p>
        <p><strong>Gelirlerimiz:</strong> <u><?php echo $conf["site_name"]; ?></u> hiçbir kurum ve kuruluştan ücret temin etmemektedir. Eğer <u><?php echo $conf["site_name"]; ?>'e destek olmak isterseniz; "Bağış" sayfası bölümünden destek olabilirsiniz.</u></p>
        <h3>2. Veri İlkemiz ve Gizililik Seçeneklerimiz</h3>
        <p>Ziyaretçilerimizden hiçbir şekilde kişisel veri almıyoruz. Üyelerimizden ise sadece birtakım bilgileri alıyoruz. Bu bilgiler; kullanıcıya ait IP adresi, eposta adresi, isim, soyisim, kullanıcı adı gibi kişisel verilerini alıyoruz. Bu bilgileri hiçbir şekilde üçüncü kişilere paylaşmıyoruz.</p>
        <p><strong>Arama Motorları'ndaki aramalar:</strong> Ziyaretçilerimizin ve üyelerimizin arama terimlerini saklıyoruz. Daha iyi bir hizmet verebilmek için depoluyoruz. Sadece ve sadece arama terimlerini depoluyoruz. Ziyaretçilere ve üyelerimize ait kişisel verileri ve arama terimlerini karşılaştırmıyoruz. <u><?php echo $conf["site_name"]; ?></u> yetkililerin arama terimlerini ve kişisel bilgileri karşılaştırma gibi bir hakkı yoktur. Aranılan terimler, hiçbir şekilde üçüncü kişilere paylaşmıyoruz. <u><?php echo $conf["site_name"]; ?></u>'in üçüncü kişilere paylaşma gibi hakkı söz konusu değildir. Paylaşımı yapan yetkili tespit edilirse, <u><?php echo $conf["site_name"]; ?></u> ile arasında olan bağları kopartılacaktır.</p>
        <p><strong>Not Defteri Kayıtları:</strong> Ziyaretçiler tarafından girilen veriler, Çerezler'de depolanmaktadır. Bu durumda ziyaretçilerin bilgileri güvenli değildir. Aynı bilgisayarı kullanan bir başka kişi istediği takdirde çok rahat bir şekilde kişisel bilgilere ulaşacaktır. Bu güvenlik ihlalinden oluşabilecek sorumlulukları kabul etmiyoruz. Üyelerimizin verileri, <u><?php echo $conf["site_name"]; ?></u> sunucularında depolanmaktadır. <u><?php echo $conf["site_name"]; ?></u> sunucularında siber saldırıdan ötürü oluşabilecek güvenlik açıklarından <u><?php echo $conf["site_name"]; ?></u> yetkilileri sorumludur. Bu sorumluluğu kabul etmeden önce saldırı yaşandığını beyan etmemiz gerekir. Aksi takdirde bu sorumluluk kabul edilmeyecektir.</p>
        <p><strong>Paylaşım:</strong> <u><?php echo $conf["site_name"]; ?></u> içeriklerindeki yapılan paylaşımlar sadece ve sadece kişisel kullanıma yöneliktir. Bir başka üyeye/ziyaretçiye ait bir bilgiyi <u><?php echo $conf["site_name"]; ?></u>'de göremezsiniz. <u><?php echo $conf["site_name"]; ?></u> kişisel kullanıma yönelik hazırlanmıştır.</p>
        <h3>3. <?php echo $conf["site_name"]; ?> Hizmetlerinden Kimler Faydalanabilir?</h3>
        <p><u><?php echo $conf["site_name"]; ?></u> hizmetlerinden, internet ve tarayıcı desteği olan cihazlar faydalanabilir. <u><?php echo $conf["site_name"]; ?></u> hizmetlerinden her yaş grubu faydalanabilir fakat biz kullanacak kullanıcılarımızın en az 6 yaşında tavsiye ediyoruz. Eğer yürürlükteki yasalar gereği ürün, hizmet ve yazılımlarımızdan mahrum kaldığınıza dair tespitte bulunursak, kullanıcıya beyan etmeden hesabını devredışı bırakacağız.</p>
        <p><strong>Yasal Olmayan İçerikler:</strong> Pornografi, cinayet, uyuşturucu, kumar vb. yasadışı içeriklere özendirebilecek içeriklerden <u><?php echo $conf["site_name"]; ?></u> yönetimi kendi iradesiyle paylaşmadığı sürece kabul etmez. Ancak <u><?php echo $conf["site_name"]; ?></u>'de bu tür içeriklerin olmayacağı anlamına gelmez. Bu içerikler hizmet aldığımız internet siteleri tarafından yayımlanırsa, <u><?php echo $conf["site_name"]; ?></u> sorumluluk kabul etmez. Biz içeriklerimizin %80'ini başka internet sitelerinden temin ediyoruz. Bu internet sitelerinin verilerini değiştirmek gibi bir hakkımız bulunmamaktadır.</p>
        <p><strong>Reklam Verileri:</strong> <u><?php echo $conf["site_name"]; ?></u> ilkelerini güncellemediği sürece kişisel bilgileri reklam şirketlerine verme gibi bir hakkı bulunmamaktadır. İleriki zamanda böyle bir girişimde bulunulabiliriz. Böyle bir girişimimiz olduğu takdirde, "Site Kullanma Koşulları" makalemizi tekrardan beyan etmek zorundayız. Tekrardan elden geçen makale kullanıcıların bilgisine sunulur ve hizmeti kullanıp kullanmamak kullanıcıya ait olur.</p>
        <p><strong>Kullanım Koşulları Güncellemesi:</strong> Bu koşulları beyan etmeden güncelleyemeyiz. Ancak değiştirilecek ise, önce yeni kullanım koşulları düzenlenir, geçerli olacak tarih belirlenir ve kullanıcılarımıza beyan edilir. Kullanıcılara beyan edilmeyen "Kullanım koşulları"'ndan kullanıcı sorumlu değildir. Ancak bu koşulların güncellenme bilgisi "Makale" bölümü altından paylaşılacaktır ve kullanıcılarımıza bildiri gönderilecektir. "Makale" sayfamızı takip etmenizi tavsiye ederiz.</p>
        <p><strong>Cezalar:</strong> Kullanıcı cezalandırılacaktır. Birinci ihtarda 7 gün, ikinci ihtarda 14 gün, üçüncü ihtarda 30 gün, dördüncü ihtarda 90 gün ve beşinci ihtarda süresiz olmak üzere cezalandırılacaktır. verilen bu cezalar kullanıcılara bildirilecektir. Süresiz uzaklaştırılan kullanıcı yine <u><?php echo $conf["site_name"]; ?></u> hizmetlerini kullanmaya devam ederse, diğer hesapları anında devre dışı bırakılacaktır.</p>
        <hr>
        <p><i><u><?php echo $conf["site_name"]; ?></u> koşulları 07/06/2019 tarihi itibariyle düzenlenmiş olup, 15/06/2019 tarihinde yürürlüğe girecektir.</i></p>
    </section>
</section>
<?php require_once(__DIR__.'/inc/footer.php'); ?>